In [ ]:
import pandas as pd

In [ ]:
ev = pd.read_csv('./Vehicle Data.csv')

In [ ]:
ev.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
0,Alabama,"13,000","5,800","63,300","54,200","441,200",100,100,0,0,"4,102,200","127,000","29,000"
1,Alaska,"2,700",900,"10,600","9,600","46,800",0,0,0,0,"454,300","29,800","5,100"
2,Arizona,"89,800","25,600","175,700","68,600","437,100",600,700,0,0,"5,469,000","197,700","64,200"
3,Arkansas,"7,100","3,200","37,000","37,000","276,700",200,0,0,0,"2,246,100","90,700","10,300"
4,California,"1,256,600","410,700","1,703,200","201,600","1,314,600","10,100","1,500","16,900",0,"31,191,900","735,300","7,900"

In [ ]:
ev['Methanol'].describe()

count    51.0
mean      0.0
std       0.0
min       0.0
25%       0.0
50%       0.0
75%       0.0
max       0.0
Name: Methanol, dtype: float64

In [ ]:
ev.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           51 non-null     str
 1   Electric (EV)                   51 non-null     str
 2   Plug-In Hybrid Electric (PHEV)  51 non-null     str
 3   Hybrid Electric (HEV)           51 non-null     str
 4   Biodiesel                       51 non-null     str
 5   Ethanol/Flex (E85)              51 non-null     str
 6   Compressed Natural Gas (CNG)    51 non-null     str
 7   Propane                         51 non-null     str
 8   Hydrogen                        51 non-null     str
 9   Methanol                        51 non-null     int64
 10  Gasoline                        51 non-null     str
 11  Diesel                          51 non-null     str
 12  Unknown Fuel                    51 non-null     str
dtypes: int64(1), str(12)
memory usage: 8.6 KB

In [ ]:
conversion_columns = ['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane',
                      'Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']

In [ ]:
ev[conversion_columns] = ev[conversion_columns].replace({r'\$': '', r',': ''}, regex=True)

In [ ]:
ev[conversion_columns] = ev[conversion_columns].astype(float)

In [ ]:
ev.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           51 non-null     str
 1   Electric (EV)                   51 non-null     float64
 2   Plug-In Hybrid Electric (PHEV)  51 non-null     float64
 3   Hybrid Electric (HEV)           51 non-null     float64
 4   Biodiesel                       51 non-null     float64
 5   Ethanol/Flex (E85)              51 non-null     float64
 6   Compressed Natural Gas (CNG)    51 non-null     float64
 7   Propane                         51 non-null     float64
 8   Hydrogen                        51 non-null     float64
 9   Methanol                        51 non-null     float64
 10  Gasoline                        51 non-null     float64
 11  Diesel                          51 non-null     float64
 12  Unknown Fuel                    51 non-null     float64
dtypes: float64(12), str(1)
memory usage: 5.7 KB

In [ ]:
ev['State'].unique()

<ArrowStringArray>
[             'Alabama',               'Alaska',              'Arizona',
             'Arkansas',           'California',             'Colorado',
          'Connecticut',             'Delaware', 'District of Columbia',
              'Florida',              'Georgia',               'Hawaii',
                'Idaho',             'Illinois',              'Indiana',
                 'Iowa',               'Kansas',             'Kentucky',
            'Louisiana',                'Maine',             'Maryland',
        'Massachusetts',             'Michigan',            'Minnesota',
          'Mississippi',             'Missouri',              'Montana',
             'Nebraska',               'Nevada',        'New Hampshire',
           'New Jersey',           'New Mexico',             'New York',
       'North Carolina',         'North Dakota',                 'Ohio',
             'Oklahoma',               'Oregon',         'Pennsylvania',
         'Rhode Island',       'South Carolina',         'South Dakota',
            'Tennessee',                'Texas',                 'Utah',
              'Vermont',             'Virginia',           'Washington',
        'West Virginia',            'Wisconsin',              'Wyoming']
Length: 51, dtype: str

In [ ]:
ev.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
0,Alabama,13000.0,5800.0,63300.0,54200.0,441200.0,100.0,100.0,0.0,0.0,4102200.0,127000.0,29000.0
1,Alaska,2700.0,900.0,10600.0,9600.0,46800.0,0.0,0.0,0.0,0.0,454300.0,29800.0,5100.0
2,Arizona,89800.0,25600.0,175700.0,68600.0,437100.0,600.0,700.0,0.0,0.0,5469000.0,197700.0,64200.0
3,Arkansas,7100.0,3200.0,37000.0,37000.0,276700.0,200.0,0.0,0.0,0.0,2246100.0,90700.0,10300.0
4,California,1256600.0,410700.0,1703200.0,201600.0,1314600.0,10100.0,1500.0,16900.0,0.0,31191900.0,735300.0,7900.0

In [ ]:
ev[['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 
   'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane','Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']].sum()

Electric (EV)                       3555900.0
Plug-In Hybrid Electric (PHEV)      1307200.0
Hybrid Electric (HEV)               7392300.0
Biodiesel                           2803600.0
Ethanol/Flex (E85)                 20240600.0
Compressed Natural Gas (CNG)          24700.0
Propane                                6000.0
Hydrogen                              16900.0
Gasoline                          242870900.0
Diesel                              7184300.0
Unknown Fuel                        1694100.0
Methanol                                  0.0
dtype: float64

In [ ]:
all_vehicles = ['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 
   'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane','Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']

In [ ]:
sum_of_all_vehicles = ev[all_vehicles].sum()
sum_of_all_vehicles.sum()
## 287,096,500 - total vehicles ##

np.float64(287096500.0)

In [ ]:
(ev[['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 
   'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane','Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']].sum() / sum_of_all_vehicles.sum() * 100).round(3)
## percentages of cars by their type across all states ##

Electric (EV)                      1.239
Plug-In Hybrid Electric (PHEV)     0.455
Hybrid Electric (HEV)              2.575
Biodiesel                          0.977
Ethanol/Flex (E85)                 7.050
Compressed Natural Gas (CNG)       0.009
Propane                            0.002
Hydrogen                           0.006
Gasoline                          84.596
Diesel                             2.502
Unknown Fuel                       0.590
Methanol                           0.000
dtype: float64

In [ ]:
ev.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
0,Alabama,13000.0,5800.0,63300.0,54200.0,441200.0,100.0,100.0,0.0,0.0,4102200.0,127000.0,29000.0
1,Alaska,2700.0,900.0,10600.0,9600.0,46800.0,0.0,0.0,0.0,0.0,454300.0,29800.0,5100.0
2,Arizona,89800.0,25600.0,175700.0,68600.0,437100.0,600.0,700.0,0.0,0.0,5469000.0,197700.0,64200.0
3,Arkansas,7100.0,3200.0,37000.0,37000.0,276700.0,200.0,0.0,0.0,0.0,2246100.0,90700.0,10300.0
4,California,1256600.0,410700.0,1703200.0,201600.0,1314600.0,10100.0,1500.0,16900.0,0.0,31191900.0,735300.0,7900.0

In [ ]:
ev.sum(axis=1, numeric_only=True).head()

0     4835900.0
1      559800.0
2     6529000.0
3     2708300.0
4    36850300.0
dtype: float64

In [ ]:
ev['Total_Vehicles'] = ev[['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 
   'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane','Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']].sum(axis=1)

In [ ]:
state_summary = ev[['State', 'Total_Vehicles']]

In [ ]:
state_summary.head()

        State  Total_Vehicles
0     Alabama       4835900.0
1      Alaska        559800.0
2     Arizona       6529000.0
3    Arkansas       2708300.0
4  California      36850300.0

In [ ]:
ev['part_of_total_by_state'] = (ev['Total_Vehicles'] / ev['Total_Vehicles'].sum() * 100).round(3)

In [ ]:
state_divided_by_total = ev[['State', 'part_of_total_by_state']]

In [ ]:
state_divided_by_total.sort_values(by='part_of_total_by_state', ascending=False)
## percentage of cars in each state of the total amount of cars in the US ##

                   State  part_of_total_by_state
4             California                  12.836
43                 Texas                   8.985
9                Florida                   6.473
32              New York                   3.942
35                  Ohio                   3.594
38          Pennsylvania                   3.557
13              Illinois                   3.498
10               Georgia                   3.359
33        North Carolina                   3.165
22              Michigan                   2.970
46              Virginia                   2.690
30            New Jersey                   2.551
47            Washington                   2.374
42             Tennessee                   2.278
2                Arizona                   2.274
14               Indiana                   2.150
25              Missouri                   1.960
49             Wisconsin                   1.926
21         Massachusetts                   1.913
5               Colorado                   1.895
23             Minnesota                   1.783
20              Maryland                   1.762
40        South Carolina                   1.756
0                Alabama                   1.684
36              Oklahoma                   1.494
17              Kentucky                   1.407
37                Oregon                   1.335
18             Louisiana                   1.315
15                  Iowa                   1.098
44                  Utah                   1.071
6            Connecticut                   1.026
24           Mississippi                   0.949
3               Arkansas                   0.943
16                Kansas                   0.913
28                Nevada                   0.890
12                 Idaho                   0.688
27              Nebraska                   0.687
31            New Mexico                   0.680
48         West Virginia                   0.526
29         New Hampshire                   0.482
19                 Maine                   0.431
11                Hawaii                   0.376
26               Montana                   0.356
41          South Dakota                   0.320
7               Delaware                   0.319
39          Rhode Island                   0.306
34          North Dakota                   0.278
50               Wyoming                   0.227
45               Vermont                   0.207
1                 Alaska                   0.195
8   District of Columbia                   0.109

In [ ]:
ev.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel,Total_Vehicles,part_of_total_by_state
0,Alabama,13000.0,5800.0,63300.0,54200.0,441200.0,100.0,100.0,0.0,0.0,4102200.0,127000.0,29000.0,4835900.0,1.684
1,Alaska,2700.0,900.0,10600.0,9600.0,46800.0,0.0,0.0,0.0,0.0,454300.0,29800.0,5100.0,559800.0,0.195
2,Arizona,89800.0,25600.0,175700.0,68600.0,437100.0,600.0,700.0,0.0,0.0,5469000.0,197700.0,64200.0,6529000.0,2.274
3,Arkansas,7100.0,3200.0,37000.0,37000.0,276700.0,200.0,0.0,0.0,0.0,2246100.0,90700.0,10300.0,2708300.0,0.943
4,California,1256600.0,410700.0,1703200.0,201600.0,1314600.0,10100.0,1500.0,16900.0,0.0,31191900.0,735300.0,7900.0,36850300.0,12.836

In [ ]:
ev_all_veh = ev[['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Biodiesel', 
   'Ethanol/Flex (E85)', 'Compressed Natural Gas (CNG)', 'Propane','Hydrogen', 'Gasoline', 'Diesel', 'Unknown Fuel', 'Methanol']]

In [ ]:
ev["EVs_perc"] = ((ev["Electric (EV)"] / ev['Total_Vehicles']) * 100).round(3)

In [ ]:
evs_divided_by_total = ev[['State', 'EVs_perc']]

In [ ]:
evs_divided_by_total.sort_values(by='EVs_perc', ascending=False)

                   State  EVs_perc
4             California     3.410
8   District of Columbia     2.595
11                Hawaii     2.370
47            Washington     2.231
28                Nevada     1.854
30            New Jersey     1.840
37                Oregon     1.680
5               Colorado     1.656
20              Maryland     1.425
2                Arizona     1.375
9                Florida     1.372
21         Massachusetts     1.344
45               Vermont     1.315
44                  Utah     1.300
32              New York     1.160
46              Virginia     1.099
6            Connecticut     1.073
13              Illinois     0.992
10               Georgia     0.958
7               Delaware     0.918
43                 Texas     0.892
33        North Carolina     0.773
39          Rhode Island     0.729
23             Minnesota     0.725
29         New Hampshire     0.715
38          Pennsylvania     0.687
19                 Maine     0.599
22              Michigan     0.590
36              Oklahoma     0.532
31            New Mexico     0.528
42             Tennessee     0.508
35                  Ohio     0.488
1                 Alaska     0.482
25              Missouri     0.478
26               Montana     0.450
49             Wisconsin     0.450
16                Kansas     0.431
12                 Idaho     0.430
14               Indiana     0.423
40        South Carolina     0.414
27              Nebraska     0.350
17              Kentucky     0.287
15                  Iowa     0.285
0                Alabama     0.269
3               Arkansas     0.262
18             Louisiana     0.217
41          South Dakota     0.185
48         West Virginia     0.185
50               Wyoming     0.168
24           Mississippi     0.132
34          North Dakota     0.125

In [ ]:
target_columns = ['Electric (EV)', 'Plug-In Hybrid Electric (PHEV)', 'Hybrid Electric (HEV)', 'Gasoline']

In [ ]:
percentages_calc = (ev[target_columns].div(ev['Total_Vehicles'], axis=0)*100).round(3)

In [ ]:
percentages_calc = percentages_calc.add_suffix('_perc')

In [ ]:
ev = pd.concat([ev, percentages_calc], axis=1)

In [ ]:
ev.sort_values(ascending=False, by="EVs_perc")

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel,Total_Vehicles,part_of_total_by_state,EVs_perc,Electric (EV)_perc,Plug-In Hybrid Electric (PHEV)_perc,Hybrid Electric (HEV)_perc,Gasoline_perc
4,California,1256600.0,410700.0,1703200.0,201600.0,1314600.0,10100.0,1500.0,16900.0,0.0,31191900.0,735300.0,7900.0,36850300.0,12.836,3.410,3.410,1.115,4.622,84.645
8,District of Columbia,8100.0,3700.0,18100.0,400.0,16800.0,100.0,0.0,0.0,0.0,262500.0,1800.0,600.0,312100.0,0.109,2.595,2.595,1.186,5.799,84.108
11,Hawaii,25600.0,7300.0,36400.0,3400.0,37300.0,0.0,0.0,0.0,0.0,951000.0,15400.0,3700.0,1080100.0,0.376,2.370,2.370,0.676,3.370,88.047
47,Washington,152100.0,41200.0,307200.0,73800.0,337700.0,100.0,100.0,0.0,0.0,5583000.0,274200.0,46700.0,6816100.0,2.374,2.231,2.231,0.604,4.507,81.909
28,Nevada,47400.0,10600.0,69600.0,27200.0,125600.0,200.0,100.0,0.0,0.0,2169300.0,85800.0,20300.0,2556100.0,0.890,1.854,1.854,0.415,2.723,84.868
30,New Jersey,134800.0,40900.0,174200.0,27800.0,392100.0,300.0,0.0,0.0,0.0,6433000.0,84600.0,36400.0,7324100.0,2.551,1.840,1.840,0.558,2.378,87.833
37,Oregon,64400.0,28800.0,156900.0,55500.0,184600.0,100.0,100.0,0.0,0.0,3074300.0,217000.0,51000.0,3832700.0,1.335,1.680,1.680,0.751,4.094,80.212
5,Colorado,90100.0,37500.0,152700.0,68100.0,334300.0,300.0,100.0,0.0,0.0,4508800.0,203400.0,46500.0,5441800.0,1.895,1.656,1.656,0.689,2.806,82.855
20,Maryland,72100.0,31300.0,168700.0,32100.0,309300.0,300.0,0.0,0.0,0.0,4327800.0,86900.0,31500.0,5060000.0,1.762,1.425,1.425,0.619,3.334,85.530
2,Arizona,89800.0,25600.0,175700.0,68600.0,437100.0,600.0,700.0,0.0,0.0,5469000.0,197700.0,64200.0,6529000.0,2.274,1.375,1.375,0.392,2.691,83.765
9,Florida,254900.0,57300.0,414500.0,170500.0,1101100.0,400.0,100.0,0.0,0.0,16136500.0,351800.0,96100.0,18583200.0,6.473,1.372,1.372,0.308,2.231,86.834
21,Massachusetts,73800.0,43800.0,187300.0,21300.0,285000.0,200.0,0.0,0.0,0.0,4791300.0,58400.0,30000.0,5491100.0,1.913,1.344,1.344,0.798,3.411,87.256
45,Vermont,7800.0,5700.0,20300.0,7000.0,36600.0,0.0,0.0,0.0,0.0,496000.0,14700.0,5000.0,593100.0,0.207,1.315,1.315,0.961,3.423,83.628
44,Utah,40000.0,13000.0,83200.0,68500.0,185200.0,2200.0,500.0,0.0,0.0,2499600.0,158000.0,26000.0,3076200.0,1.071,1.300,1.300,0.423,2.705,81.256
32,New York,131300.0,92300.0,314000.0,54300.0,591100.0,400.0,100.0,0.0,0.0,9905500.0,150500.0,79100.0,11318600.0,3.942,1.160,1.160,0.815,2.774,87.515
46,Virginia,84900.0,26800.0,229400.0,44300.0,484800.0,300.0,0.0,0.0,0.0,6670000.0,152800.0,30200.0,7723500.0,2.690,1.099,1.099,0.347,2.970,86.360
6,Connecticut,31600.0,18400.0,75300.0,10900.0,133600.0,100.0,0.0,0.0,0.0,2612600.0,42300.0,20900.0,2945700.0,1.026,1.073,1.073,0.625,2.556,88.692
13,Illinois,99600.0,33400.0,285400.0,61500.0,772900.0,300.0,0.0,0.0,0.0,8560300.0,170200.0,59600.0,10043200.0,3.498,0.992,0.992,0.333,2.842,85.235
10,Georgia,92400.0,22700.0,175300.0,92500.0,719400.0,300.0,200.0,0.0,0.0,8256400.0,206300.0,76900.0,9642400.0,3.359,0.958,0.958,0.235,1.818,85.626
7,Delaware,8400.0,3800.0,22900.0,5100.0,63900.0,0.0,0.0,0.0,0.0,791300.0,14200.0,5100.0,914700.0,0.319,0.918,0.918,0.415,2.504,86.509
43,Texas,230100.0,55300.0,445100.0,460700.0,2315400.0,1300.0,1300.0,0.0,0.0,21392800.0,772800.0,121800.0,25796600.0,8.985,0.892,0.892,0.214,1.725,82.929
33,North Carolina,70200.0,23700.0,210600.0,80200.0,655000.0,300.0,100.0,0.0,0.0,7764000.0,209700.0,71700.0,9085500.0,3.165,0.773,0.773,0.261,2.318,85.455
39,Rhode Island,6400.0,5100.0,22100.0,3100.0,41900.0,0.0,0.0,0.0,0.0,782000.0,11000.0,6000.0,877600.0,0.306,0.729,0.729,0.581,2.518,89.107
23,Minnesota,37100.0,16100.0,124500.0,52700.0,516400.0,100.0,0.0,0.0,0.0,4219200.0,127900.0,24500.0,5118500.0,1.783,0.725,0.725,0.315,2.432,82.430
29,New Hampshire,9900.0,6600.0,36800.0,13900.0,89600.0,100.0,0.0,0.0,0.0,1185300.0,29200.0,12300.0,1383700.0,0.482,0.715,0.715,0.477,2.660,85.662
38,Pennsylvania,70200.0,38900.0,245400.0,73900.0,661700.0,500.0,100.0,0.0,0.0,8886400.0,192100.0,41800.0,10211000.0,3.557,0.687,0.687,0.381,2.403,87.028
19,Maine,7400.0,7600.0,33600.0,12000.0,104500.0,0.0,0.0,0.0,0.0,1036100.0,26900.0,7900.0,1236000.0,0.431,0.599,0.599,0.615,2.718,83.827
22,Michigan,50300.0,29100.0,148100.0,70400.0,873700.0,300.0,0.0,0.0,0.0,7129600.0,174500.0,49400.0,8525400.0,2.970,0.590,0.590,0.341,1.737,83.628
36,Oklahoma,22800.0,33000.0,56400.0,63100.0,352400.0,1800.0,200.0,0.0,0.0,3567500.0,145700.0,45000.0,4287900.0,1.494,0.532,0.532,0.770,1.315,83.199
31,New Mexico,10300.0,4900.0,44300.0,32100.0,151600.0,100.0,100.0,0.0,0.0,1597600.0,88500.0,22900.0,1952400.0,0.680,0.528,0.528,0.251,2.269,81.827
42,Tennessee,33200.0,11000.0,113300.0,53100.0,509000.0,200.0,100.0,0.0,0.0,5620500.0,160700.0,37700.0,6538800.0,2.278,0.508,0.508,0.168,1.733,85.956
35,Ohio,50400.0,24000.0,199800.0,70300.0,833500.0,700.0,100.0,0.0,0.0,8881400.0,196200.0,60900.0,10317300.0,3.594,0.488,0.488,0.233,1.937,86.083
1,Alaska,2700.0,900.0,10600.0,9600.0,46800.0,0.0,0.0,0.0,0.0,454300.0,29800.0,5100.0,559800.0,0.195,0.482,0.482,0.161,1.894,81.154
25,Missouri,26900.0,13900.0,113900.0,70400.0,575500.0,900.0,100.0,0.0,0.0,4608600.0,178200.0,37600.0,5626000.0,1.960,0.478,0.478,0.247,2.025,81.916
26,Montana,4600.0,2500.0,21100.0,37900.0,94500.0,0.0,0.0,0.0,0.0,780700.0,69600.0,10800.0,1021700.0,0.356,0.450,0.450,0.245,2.065,76.412
49,Wisconsin,24900.0,12500.0,123600.0,52900.0,536200.0,300.0,0.0,0.0,0.0,4604700.0,147500.0,26400.0,5529000.0,1.926,0.450,0.450,0.226,2.235,83.283
16,Kansas,11300.0,5600.0,50400.0,27900.0,253500.0,200.0,100.0,0.0,0.0,2168600.0,87400.0,16100.0,2621100.0,0.913,0.431,0.431,0.214,1.923,82.736
12,Idaho,8500.0,4600.0,43700.0,45900.0,132900.0,100.0,100.0,0.0,0.0,1568600.0,138600.0,31600.0,1974600.0,0.688,0.430,0.430,0.233,2.213,79.439
14,Indiana,26100.0,12900.0,119100.0,56300.0,576300.0,300.0,0.0,0.0,0.0,5166200.0,156400.0,58500.0,6172100.0,2.150,0.423,0.423,0.209,1.930,83.702
40,South Carolina,20900.0,9000.0,83100.0,44600.0,404600.0,100.0,100.0,0.0,0.0,4325000.0,110100.0,44900.0,5042400.0,1.756,0.414,0.414,0.178,1.648,85.773
27,Nebraska,6900.0,3800.0,32600.0,28900.0,197100.0,100.0,0.0,0.0,0.0,1600400.0,76100.0,25300.0,1971200.0,0.687,0.350,0.350,0.193,1.654,81.189
17,Kentucky,11600.0,5600.0,67100.0,36900.0,361200.0,300.0,0.0,0.0,0.0,3415000.0,117600.0,24400.0,4039700.0,1.407,0.287,0.287,0.139,1.661,84.536
15,Iowa,9000.0,6100.0,57200.0,41700.0,331300.0,100.0,0.0,0.0,0.0,2545400.0,105000.0,57500.0,3153300.0,1.098,0.285,0.285,0.193,1.814,80.722
0,Alabama,13000.0,5800.0,63300.0,54200.0,441200.0,100.0,100.0,0.0,0.0,4102200.0,127000.0,29000.0,4835900.0,1.684,0.269,0.269,0.120,1.309,84.828
3,Arkansas,7100.0,3200.0,37000.0,37000.0,276700.0,200.0,0.0,0.0,0.0,2246100.0,90700.0,10300.0,2708300.0,0.943,0.262,0.262,0.118,1.366,82.934
18,Louisiana,8200.0,4000.0,40200.0,64200.0,380100.0,100.0,0.0,0.0,0.0,3142800.0,115500.0,19100.0,3774200.0,1.315,0.217,0.217,0.106,1.065,83.271
41,South Dakota,1700.0,1300.0,11900.0,21500.0,98800.0,0.0,0.0,0.0,0.0,718300.0,51200.0,13300.0,918000.0,0.320,0.185,0.185,0.142,1.296,78.246
48,West Virginia,2800.0,1800.0,22400.0,17300.0,123400.0,100.0,0.0,0.0,0.0,1281500.0,46400.0,15200.0,1510900.0,0.526,0.185,0.185,0.119,1.483,84.817
50,Wyoming,1100.0,800.0,8400.0,21200.0,57700.0,0.0,0.0,0.0,0.0,489100.0,60900.0,13700.0,652900.0,0.227,0.168,0.168,0.123,1.287,74.912
24,Mississippi,3600.0,2000.0,28200.0,34900.0,295200.0,100.0,0.0,0.0,0.0,2275600.0,75200.0,8500.0,2723300.0,0.949,0.132,0.132,0.073,1.036,83.560
34,North Dakota,1000.0,800.0,8200.0,20400.0,89900.0,0.0,0.0,0.0,0.0,625300.0,44600.0,7200.0,797400.0,0.278,0.125,0.125,0.100,1.028,78.417

In [ ]:
from scipy.stats import pearsonr

In [ ]:
ev.columns

Index(['State', 'Electric (EV)', 'Plug-In Hybrid Electric (PHEV)',
       'Hybrid Electric (HEV)', 'Biodiesel', 'Ethanol/Flex (E85)',
       'Compressed Natural Gas (CNG)', 'Propane', 'Hydrogen', 'Methanol',
       'Gasoline', 'Diesel', 'Unknown Fuel', 'Total_Vehicles',
       'part_of_total_by_state', 'EVs_perc', 'Electric (EV)_perc',
       'Plug-In Hybrid Electric (PHEV)_perc', 'Hybrid Electric (HEV)_perc',
       'Gasoline_perc'],
      dtype='str')

In [ ]:
alt_fuels = ['Biodiesel', 'Ethanol/Flex (E85)', 'Hydrogen']

In [ ]:
all_alt_fuels_sum = ev[alt_fuels].sum()

In [ ]:
sum_of_all_vehicles.sum()

np.float64(287096500.0)

In [ ]:
alt_market_share = ((all_alt_fuels_sum.sum() / sum_of_all_vehicles.sum() ) * 100).round(3)

In [ ]:
alt_market_share

np.float64(8.033)

In [ ]:
alt_market_share_str = f"{alt_market_share:.3f}% - out of all vehicles"

In [ ]:
alt_market_share_str

'8.033% - out of all vehicles'

In [ ]:
ev.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel,Total_Vehicles,part_of_total_by_state,EVs_perc,Electric (EV)_perc,Plug-In Hybrid Electric (PHEV)_perc,Hybrid Electric (HEV)_perc,Gasoline_perc
0,Alabama,13000.0,5800.0,63300.0,54200.0,441200.0,100.0,100.0,0.0,0.0,4102200.0,127000.0,29000.0,4835900.0,1.684,0.269,0.269,0.120,1.309,84.828
1,Alaska,2700.0,900.0,10600.0,9600.0,46800.0,0.0,0.0,0.0,0.0,454300.0,29800.0,5100.0,559800.0,0.195,0.482,0.482,0.161,1.894,81.154
2,Arizona,89800.0,25600.0,175700.0,68600.0,437100.0,600.0,700.0,0.0,0.0,5469000.0,197700.0,64200.0,6529000.0,2.274,1.375,1.375,0.392,2.691,83.765
3,Arkansas,7100.0,3200.0,37000.0,37000.0,276700.0,200.0,0.0,0.0,0.0,2246100.0,90700.0,10300.0,2708300.0,0.943,0.262,0.262,0.118,1.366,82.934
4,California,1256600.0,410700.0,1703200.0,201600.0,1314600.0,10100.0,1500.0,16900.0,0.0,31191900.0,735300.0,7900.0,36850300.0,12.836,3.410,3.410,1.115,4.622,84.645

In [ ]:
ev[alt_fuels].sum()

Biodiesel              2803600.0
Ethanol/Flex (E85)    20240600.0
Hydrogen                 16900.0
dtype: float64

In [ ]:
alt_fuels_percentages = ((ev[alt_fuels].sum() / sum_of_all_vehicles.sum()) * 100).round(3)

In [ ]:
alt_fuels_percentages

Biodiesel             0.977
Ethanol/Flex (E85)    7.050
Hydrogen              0.006
dtype: float64

In [ ]:
ev.head()